name: chronaris-stage-e-cpu
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  - packaging
  - pyyaml
  - setuptools
  - numpy=2.0.1
  - pytorch=2.5.1
  - cpuonly
  - pip:
      - torchdiffeq==0.2.2
